# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "J On The Beach 2016"
email: "info@jonthebeach.com"
description: "Bringing developers and devOps together around the JVM"
baseurl: ""
url: "http://www.jonthebeach.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "www.jonthebeach.com"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Jelastic & Valo"
organizerAlternateName: "Jelastic & Valo"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "info@jonthebeach.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.valo.io"

# Head
metaKeywords: "event, JVM, scala, Gosling, JAVA8, developers, devOps, Málaga, devfest, programming"
twitterAccount: "@J_OnTheBeach"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {permalink: "/schedule/", text: "Schedule"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "A JVM rendezvous for <typeout>"
eventDate: "March 18th-19th, 2016"
typeoutTextValues: '"", "Scala developers", "devOps", "Java lovers", "Groovy"'
typeoutFallback: "Software enthusiasts"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About J On The Beach"
aboutBlock:
 - {title: "The Rendezvous", image: "conference.jpg", text: "A meeting to share experiences and knowledge with top programmers from all over the world around the JVM." }
 - {title: "The City", image: "workshop.jpg", text: "Málaga, a dynamic metropolis on the southern coast of Spain with one of the best climates in Europe." }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "400", specialCharacter: "+", info: "attendees", detail: "from all over"}
 - {count: "20", specialCharacter: "+", info: "hours", detail: "of JVM madness"}
 - {count: "38", specialCharacter: "+", info: "speakers", detail: "from around the globe"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "plus Workshops"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "La Térmica. Málaga"
eventLocationLink: "https://plus.google.com/101376405204347992216/posts?gl=es&hl=es"
eventStreetAddress: "Av. de Los Guindos, 48. Next to La Misericordia Beach"
eventAddressLocality: "Málaga"
eventAddressLocalityRegion: "Andalucía"
eventPostalCode: "29004"
eventAddressCountry: "Spain"
eventStartTime: "2016-03-18T09:00"
eventDoorTime: "08:30"
eventEndTime: "2016-03-19T19:30"
eventPlaceCoordinates: "36.6894372, -4.4452808"
mapCenterCoordinates: "36.6894372, -4.4452808"
mapMobileCenterCoordinates: "36.6894372, -4.4452808"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "La Térmica"
venueFeatures: ["Mindblowing space for creators", "A life place for talents", "Located in the city of Málaga"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Talk to us!"
twitterHashTag: "jonthebeach"
# twitterFeed: "http://enterwebdesign.es/blog_jgc/tweetledee/searchjson.php?q=J_OnTheBeach"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will open in December. The number of tickets will be limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sessions and exhibition area, coffee breaks, lunch, and the closing party. Accommodations are NOT included in the ticket price."
ticketsOffers:
 -
  name: "Standard"
  price: "150"
  priceCurrency: "€"
  ticketsNumber: "200"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["All the sessions and exhibition area", "Breakfast & Lunch included", "Closing party and beers included"]
  validFrom: "2016-01-15T00:00"
  validThrough: "2016-02-29T23:59"
  disabled: true
  soldOut: false
  soldOutText: "Sold Out"

 -
  name: "Early Bird"
  price: "100"
  priceCurrency: "€"
  ticketsNumber: "100"
  ribbon: "-30%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["All the sessions and exhibition area", "Breakfast & Lunch included", "Closing party and beers included"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
  disabled: false
  featured: true
  soldOut: false
  soldOutText: "Sold Out"
 -
#  name: "Last Chance"
#  price: "200"
#  priceCurrency: "€"
#  ticketsNumber: "100"
#  featured: true
#  buyButtonLink: "http://www.eventbrite.es/e/lambda-world-tickets-18395382083"
#  buyButtonText: "Buy Now"
#  ticketContentList:  ["All the sessions and exhibition area", "Breakfast & Lunch included", "Closing party and beers included"]
#  validFrom: "2015-10-01T00:00"
#  validThrough: "2015-10-23T23:59"
#  disabled: true
# - 
  name: "Student / Unemployed"
  price: "75"
  ribbon: "-50%"
  priceCurrency: "€"
  ticketsNumber: "50"
  buyButtonLink: "http://www.eventbrite.es/e/lambda-world-tickets-18395382083"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in or a unemployement certificate. Without it, ticket will be cancelled without refund"
  ticketContentList:  ["All the sessions and exhibition area", "Breakfast & Lunch included", "Closing party and beers included"]
  validFrom: "2015-12-01T00:00"
  validThrough: "2015-03-17T23:59"
  disabled: false
  soldOut: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/b/113729645880846425767/113729645880846425767/posts/p/pub", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=J_OnTheBeach", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.jelastic.com", text: "Jelastic"}
   - {link: "http://www.valo.io", text: "VALO"}
   - {link: "http://www.meetup.com/Malaga-Scala/", text: "Scala User Group - Malaga"}
   - {link: "http://www.meetup.com/es/yeswetech/", text: "Yes We Tech - Malaga"}
   - {link: "http://www.meetup.com/es/MalagaJUG/", text: "Java User Group - Malaga"}
   - {link: "http://www.meetup.com/MadridJUG/", text: "Java User Group - Madrid"}
   - {link: "http://www.meetup.com/Scala-Programming-Madrid/", text: "Scala User Group - Madrid"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@jonthebeach.com", text: "info@jonthebeach.com"}
 -
  title: "FAQ"
  links:
   - {link: "http://berlincodeofconduct.org/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "J_OnTheBeach"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "The organizers of J On The Beach are made up of lovers of functional programming. A heterogeneous group who see this paradigm as the future of software development."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "36.6894372, -4.4452808"
logisticsMapMobileCenterCoordinates: "36.6894372, -4.4452808"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Many bus lines connect the airport with the city centre of Jerez de la Frontera and the city of Cádiz. More information is available at <a href="http://www.aena.es/csee/Satellite/Aeropuerto-Jerez/en/Page/1237554508311//Public-transport.html">AENA</a>.'}
 - {title: "By Train", information: 'The train station is just off the Plaza de Sevilla with up to 20 trains running daily to and from El Puerto de Santa Maria and Jerez de la Frontera and up to 12 regional lines to and from Seville. There are four long distance trains daily to and from Cordoba and two each for Madrid and Barcelona.'}
 - {title: "Hotels", information: 'Málaga has many fantastic hotels. The event is in the off season so prices and availability will be favorable. Below you will find a few recommendations'}
directionDetailsWideCards:
 -
  title: "Málaga"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://www.vinccimalaga.com/", text: "Hotel Vincci Málaga"}
     - {link: "http://www.ilunionhotels.com/hotel-ilunion-malaga-en-malaga", text: "Hotel Ilunion Malaga"}
     - {link: "http://www.hotelsolymar-malaga.com/", text: "Hotel Solymar Málaga"}
   -
    title: "Excellent restaurants"
    links:
     - {link: "http://www.chupytira.es/", text: "Marisquería chupytira"}
     - {link: "http://rociotapasysushi.com/", text: "Rocío Tapas & Sushi"}
     - {link: "http://www.restauranteelbotijo.com/", text: "El Botijo"}
   -
    title: "Some unknown places"
    links:
     - {link: "www.coleccionmuseoruso.es", text: "Russian Museum"}
     - {link: "https://es.wikipedia.org/wiki/Santuario_de_la_Victoria_(M%C3%A1laga)", text: "Pantheon of the Counts of BuenaVista"}
     - {link: "http://www.malagaturismo.com/es/recursos-turisticos/detalle/cementerio-ingles/52", text: "English Cemetery"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
